// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: pb/account/account.proto

package account

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountGRPCService_ExecuteTransferMutation_FullMethodName = "/account.AccountGRPCService/ExecuteTransferMutation"
	AccountGRPCService_ExecuteTopupMutation_FullMethodName    = "/account.AccountGRPCService/ExecuteTopupMutation"
)

// AccountGRPCServiceClient is the client API for AccountGRPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountGRPCServiceClient interface {
	// RPC baru untuk mengeksekusi mutasi transfer sekaligus validasi
	ExecuteTransferMutation(ctx context.Context, in *TransferMutationRequest, opts ...grpc.CallOption) (*TransferMutationResponse, error)
	// RPC baru untuk penambahan saldo
	ExecuteTopupMutation(ctx context.Context, in *TopupMutationRequest, opts ...grpc.CallOption) (*TopupMutationResponse, error)
}

type accountGRPCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountGRPCServiceClient(cc grpc.ClientConnInterface) AccountGRPCServiceClient {
	return &accountGRPCServiceClient{cc}
}

func (c *accountGRPCServiceClient) ExecuteTransferMutation(ctx context.Context, in *TransferMutationRequest, opts ...grpc.CallOption) (*TransferMutationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferMutationResponse)
	err := c.cc.Invoke(ctx, AccountGRPCService_ExecuteTransferMutation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountGRPCServiceClient) ExecuteTopupMutation(ctx context.Context, in *TopupMutationRequest, opts ...grpc.CallOption) (*TopupMutationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopupMutationResponse)
	err := c.cc.Invoke(ctx, AccountGRPCService_ExecuteTopupMutation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountGRPCServiceServer is the server API for AccountGRPCService service.
// All implementations must embed UnimplementedAccountGRPCServiceServer
// for forward compatibility.
type AccountGRPCServiceServer interface {
	// RPC baru untuk mengeksekusi mutasi transfer sekaligus validasi
	ExecuteTransferMutation(context.Context, *TransferMutationRequest) (*TransferMutationResponse, error)
	// RPC baru untuk penambahan saldo
	ExecuteTopupMutation(context.Context, *TopupMutationRequest) (*TopupMutationResponse, error)
	mustEmbedUnimplementedAccountGRPCServiceServer()
}

// UnimplementedAccountGRPCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountGRPCServiceServer struct{}

func (UnimplementedAccountGRPCServiceServer) ExecuteTransferMutation(context.Context, *TransferMutationRequest) (*TransferMutationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTransferMutation not implemented")
}
func (UnimplementedAccountGRPCServiceServer) ExecuteTopupMutation(context.Context, *TopupMutationRequest) (*TopupMutationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTopupMutation not implemented")
}
func (UnimplementedAccountGRPCServiceServer) mustEmbedUnimplementedAccountGRPCServiceServer() {}
func (UnimplementedAccountGRPCServiceServer) testEmbeddedByValue()                            {}

// UnsafeAccountGRPCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountGRPCServiceServer will
// result in compilation errors.
type UnsafeAccountGRPCServiceServer interface {
	mustEmbedUnimplementedAccountGRPCServiceServer()
}

func RegisterAccountGRPCServiceServer(s grpc.ServiceRegistrar, srv AccountGRPCServiceServer) {
	// If the following call panics, it indicates UnimplementedAccountGRPCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountGRPCService_ServiceDesc, srv)
}

func _AccountGRPCService_ExecuteTransferMutation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferMutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountGRPCServiceServer).ExecuteTransferMutation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountGRPCService_ExecuteTransferMutation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountGRPCServiceServer).ExecuteTransferMutation(ctx, req.(*TransferMutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountGRPCService_ExecuteTopupMutation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopupMutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountGRPCServiceServer).ExecuteTopupMutation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountGRPCService_ExecuteTopupMutation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountGRPCServiceServer).ExecuteTopupMutation(ctx, req.(*TopupMutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountGRPCService_ServiceDesc is the grpc.ServiceDesc for AccountGRPCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountGRPCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountGRPCService",
	HandlerType: (*AccountGRPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTransferMutation",
			Handler:    _AccountGRPCService_ExecuteTransferMutation_Handler,
		},
		{
			MethodName: "ExecuteTopupMutation",
			Handler:    _AccountGRPCService_ExecuteTopupMutation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/account/account.proto",
}
