// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "belajar-go/challenge/transactionSystem/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// AccountsService is an autogenerated mock type for the AccountsService type
type AccountsService struct {
	mock.Mock
}

// CreateNewAccount provides a mock function with given fields: account
func (_m *AccountsService) CreateNewAccount(account models.Account) (models.Account, error) {
	ret := _m.Called(account)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewAccount")
	}

	var r0 models.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Account) (models.Account, error)); ok {
		return rf(account)
	}
	if rf, ok := ret.Get(0).(func(models.Account) models.Account); ok {
		r0 = rf(account)
	} else {
		r0 = ret.Get(0).(models.Account)
	}

	if rf, ok := ret.Get(1).(func(models.Account) error); ok {
		r1 = rf(account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAccountById provides a mock function with given fields: id
func (_m *AccountsService) DeleteAccountById(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccountById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchAccountById provides a mock function with given fields: id
func (_m *AccountsService) FetchAccountById(id string) (models.Account, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FetchAccountById")
	}

	var r0 models.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Account, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) models.Account); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Account)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchAllAccounts provides a mock function with no fields
func (_m *AccountsService) FetchAllAccounts() ([]models.Account, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchAllAccounts")
	}

	var r0 []models.Account
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Account, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Account); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Account)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchTransactionsByAccountId provides a mock function with given fields: id, trxType
func (_m *AccountsService) FetchTransactionsByAccountId(id string, trxType string) ([]models.Transaction, error) {
	ret := _m.Called(id, trxType)

	if len(ret) == 0 {
		panic("no return value specified for FetchTransactionsByAccountId")
	}

	var r0 []models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]models.Transaction, error)); ok {
		return rf(id, trxType)
	}
	if rf, ok := ret.Get(0).(func(string, string) []models.Transaction); ok {
		r0 = rf(id, trxType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(id, trxType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PatchAccountById provides a mock function with given fields: account
func (_m *AccountsService) PatchAccountById(account models.Account) (string, error) {
	ret := _m.Called(account)

	if len(ret) == 0 {
		panic("no return value specified for PatchAccountById")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Account) (string, error)); ok {
		return rf(account)
	}
	if rf, ok := ret.Get(0).(func(models.Account) string); ok {
		r0 = rf(account)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(models.Account) error); ok {
		r1 = rf(account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAccountsService creates a new instance of AccountsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountsService {
	mock := &AccountsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
