// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "belajar-go/challenge/transactionSystem/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// BankRepository is an autogenerated mock type for the BankRepository type
type BankRepository struct {
	mock.Mock
}

// CreateBank provides a mock function with given fields: bank
func (_m *BankRepository) CreateBank(bank models.Bank) (string, error) {
	ret := _m.Called(bank)

	if len(ret) == 0 {
		panic("no return value specified for CreateBank")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Bank) (string, error)); ok {
		return rf(bank)
	}
	if rf, ok := ret.Get(0).(func(models.Bank) string); ok {
		r0 = rf(bank)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(models.Bank) error); ok {
		r1 = rf(bank)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBank provides a mock function with given fields: bankCode
func (_m *BankRepository) DeleteBank(bankCode string) error {
	ret := _m.Called(bankCode)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBank")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(bankCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllBanks provides a mock function with no fields
func (_m *BankRepository) GetAllBanks() ([]models.Bank, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllBanks")
	}

	var r0 []models.Bank
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Bank, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Bank); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Bank)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBank provides a mock function with given fields: bank
func (_m *BankRepository) UpdateBank(bank models.Bank) (string, error) {
	ret := _m.Called(bank)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBank")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Bank) (string, error)); ok {
		return rf(bank)
	}
	if rf, ok := ret.Get(0).(func(models.Bank) string); ok {
		r0 = rf(bank)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(models.Bank) error); ok {
		r1 = rf(bank)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBankRepository creates a new instance of BankRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBankRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BankRepository {
	mock := &BankRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
