// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "belajar-go/challenge/transactionSystem/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// BankService is an autogenerated mock type for the BankService type
type BankService struct {
	mock.Mock
}

// CreateNewBank provides a mock function with given fields: bank
func (_m *BankService) CreateNewBank(bank models.Bank) (models.Bank, error) {
	ret := _m.Called(bank)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewBank")
	}

	var r0 models.Bank
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Bank) (models.Bank, error)); ok {
		return rf(bank)
	}
	if rf, ok := ret.Get(0).(func(models.Bank) models.Bank); ok {
		r0 = rf(bank)
	} else {
		r0 = ret.Get(0).(models.Bank)
	}

	if rf, ok := ret.Get(1).(func(models.Bank) error); ok {
		r1 = rf(bank)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBank provides a mock function with given fields: bankCode
func (_m *BankService) DeleteBank(bankCode string) error {
	ret := _m.Called(bankCode)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBank")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(bankCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchAllBanks provides a mock function with no fields
func (_m *BankService) FetchAllBanks() ([]models.Bank, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchAllBanks")
	}

	var r0 []models.Bank
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Bank, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Bank); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Bank)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PatchBank provides a mock function with given fields: bank
func (_m *BankService) PatchBank(bank models.Bank) (string, error) {
	ret := _m.Called(bank)

	if len(ret) == 0 {
		panic("no return value specified for PatchBank")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Bank) (string, error)); ok {
		return rf(bank)
	}
	if rf, ok := ret.Get(0).(func(models.Bank) string); ok {
		r0 = rf(bank)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(models.Bank) error); ok {
		r1 = rf(bank)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBankService creates a new instance of BankService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBankService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BankService {
	mock := &BankService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
