// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "belajar-go/challenge/transactionSystem/internal/models"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TransactionService is an autogenerated mock type for the TransactionService type
type TransactionService struct {
	mock.Mock
}

// CreateTrx provides a mock function with given fields: trx
func (_m *TransactionService) CreateTrx(trx models.Transaction) (string, error) {
	ret := _m.Called(trx)

	if len(ret) == 0 {
		panic("no return value specified for CreateTrx")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Transaction) (string, error)); ok {
		return rf(trx)
	}
	if rf, ok := ret.Get(0).(func(models.Transaction) string); ok {
		r0 = rf(trx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(models.Transaction) error); ok {
		r1 = rf(trx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchAllTransactions provides a mock function with no fields
func (_m *TransactionService) FetchAllTransactions() ([]models.Transaction, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchAllTransactions")
	}

	var r0 []models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Transaction, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Transaction); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchSummaryToday provides a mock function with given fields: date
func (_m *TransactionService) FetchSummaryToday(date time.Time) ([]models.Transaction, error) {
	ret := _m.Called(date)

	if len(ret) == 0 {
		panic("no return value specified for FetchSummaryToday")
	}

	var r0 []models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time) ([]models.Transaction, error)); ok {
		return rf(date)
	}
	if rf, ok := ret.Get(0).(func(time.Time) []models.Transaction); ok {
		r0 = rf(date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = rf(date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchTransactionById provides a mock function with given fields: id
func (_m *TransactionService) FetchTransactionById(id string) (models.Transaction, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FetchTransactionById")
	}

	var r0 models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Transaction, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) models.Transaction); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Transaction)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactionService creates a new instance of TransactionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionService {
	mock := &TransactionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
