// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "belajar-go/challenge/transactionSystem/internal/models"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

// CreateTransaction provides a mock function with given fields: trx
func (_m *TransactionRepository) CreateTransaction(trx models.Transaction) (string, error) {
	ret := _m.Called(trx)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Transaction) (string, error)); ok {
		return rf(trx)
	}
	if rf, ok := ret.Get(0).(func(models.Transaction) string); ok {
		r0 = rf(trx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(models.Transaction) error); ok {
		r1 = rf(trx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllTransactions provides a mock function with no fields
func (_m *TransactionRepository) GetAllTransactions() ([]models.Transaction, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllTransactions")
	}

	var r0 []models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Transaction, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Transaction); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSummary provides a mock function with given fields: date
func (_m *TransactionRepository) GetSummary(date time.Time) ([]models.Transaction, error) {
	ret := _m.Called(date)

	if len(ret) == 0 {
		panic("no return value specified for GetSummary")
	}

	var r0 []models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time) ([]models.Transaction, error)); ok {
		return rf(date)
	}
	if rf, ok := ret.Get(0).(func(time.Time) []models.Transaction); ok {
		r0 = rf(date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = rf(date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionById provides a mock function with given fields: id
func (_m *TransactionRepository) GetTransactionById(id string) (models.Transaction, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionById")
	}

	var r0 models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Transaction, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) models.Transaction); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Transaction)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
