version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - transaction_net

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - transaction_net
    # redis data:
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: go_transaction_app
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      tempo:
        condition: service_started
    volumes:
      - .:/app
      - ./migrations:/app/migrations
    environment:
      APP_ADDR: "0.0.0.0"
      APP_PORT: ${APP_PORT}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: disable
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://tempo:4317"
      MIGRATIONS_PATH: "file:///root/migrations"
    networks:
      - transaction_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - transaction_net

  tempo:
    image: grafana/tempo:2.3.0
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./etc/tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200" # Untuk Grafana Data Source
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP (Ini yang kita pakai buat curl)
    networks:
      - transaction_net

  # Loki untuk Logging
  loki:
    image: grafana/loki:latest
    container_name: loki
    command: ["-config.file=/etc/loki/local-config.yaml"]
    volumes:
      - ./etc/loki/local-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - transaction_net

  # Grafana untuk Visualisasi
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3001:3000"
    volumes:
      - ./etc/grafana:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - tempo
      - loki
    networks:
      - transaction_net

volumes:
  postgres_data:
  redis_data:

networks:
  transaction_net:
    driver: bridge
