CREATE TABLE IF NOT EXISTS banks (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    bank_code  VARCHAR(50) NOT NULL UNIQUE,
    bank_name  VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);