// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: shared/pb/fraud/fraud.proto

package fraud

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FraudValidationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    string                 `protobuf:"bytes,3,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	DeviceId      string                 `protobuf:"bytes,6,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Channel       string                 `protobuf:"bytes,7,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FraudValidationRequest) Reset() {
	*x = FraudValidationRequest{}
	mi := &file_shared_pb_fraud_fraud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudValidationRequest) ProtoMessage() {}

func (x *FraudValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_pb_fraud_fraud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudValidationRequest.ProtoReflect.Descriptor instead.
func (*FraudValidationRequest) Descriptor() ([]byte, []int) {
	return file_shared_pb_fraud_fraud_proto_rawDescGZIP(), []int{0}
}

func (x *FraudValidationRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *FraudValidationRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *FraudValidationRequest) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *FraudValidationRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *FraudValidationRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FraudValidationRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *FraudValidationRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type FraudValidationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFraud       bool                   `protobuf:"varint,1,opt,name=is_fraud,json=isFraud,proto3" json:"is_fraud,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"` // e.g., "BLOCK", "ALLOW", "REVIEW"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FraudValidationResponse) Reset() {
	*x = FraudValidationResponse{}
	mi := &file_shared_pb_fraud_fraud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudValidationResponse) ProtoMessage() {}

func (x *FraudValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_pb_fraud_fraud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudValidationResponse.ProtoReflect.Descriptor instead.
func (*FraudValidationResponse) Descriptor() ([]byte, []int) {
	return file_shared_pb_fraud_fraud_proto_rawDescGZIP(), []int{1}
}

func (x *FraudValidationResponse) GetIsFraud() bool {
	if x != nil {
		return x.IsFraud
	}
	return false
}

func (x *FraudValidationResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *FraudValidationResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

var File_shared_pb_fraud_fraud_proto protoreflect.FileDescriptor

const file_shared_pb_fraud_fraud_proto_rawDesc = "" +
	"\n" +
	"\x1bshared/pb/fraud/fraud.proto\x12\x05fraud\"\xe8\x01\n" +
	"\x16FraudValidationRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x03 \x01(\tR\n" +
	"receiverId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1b\n" +
	"\tdevice_id\x18\x06 \x01(\tR\bdeviceId\x12\x18\n" +
	"\achannel\x18\a \x01(\tR\achannel\"d\n" +
	"\x17FraudValidationResponse\x12\x19\n" +
	"\bis_fraud\x18\x01 \x01(\bR\aisFraud\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action2d\n" +
	"\fFraudService\x12T\n" +
	"\x13ValidateTransaction\x12\x1d.fraud.FraudValidationRequest\x1a\x1e.fraud.FraudValidationResponseB\"Z my-microservices/shared/pb/fraudb\x06proto3"

var (
	file_shared_pb_fraud_fraud_proto_rawDescOnce sync.Once
	file_shared_pb_fraud_fraud_proto_rawDescData []byte
)

func file_shared_pb_fraud_fraud_proto_rawDescGZIP() []byte {
	file_shared_pb_fraud_fraud_proto_rawDescOnce.Do(func() {
		file_shared_pb_fraud_fraud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_pb_fraud_fraud_proto_rawDesc), len(file_shared_pb_fraud_fraud_proto_rawDesc)))
	})
	return file_shared_pb_fraud_fraud_proto_rawDescData
}

var file_shared_pb_fraud_fraud_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shared_pb_fraud_fraud_proto_goTypes = []any{
	(*FraudValidationRequest)(nil),  // 0: fraud.FraudValidationRequest
	(*FraudValidationResponse)(nil), // 1: fraud.FraudValidationResponse
}
var file_shared_pb_fraud_fraud_proto_depIdxs = []int32{
	0, // 0: fraud.FraudService.ValidateTransaction:input_type -> fraud.FraudValidationRequest
	1, // 1: fraud.FraudService.ValidateTransaction:output_type -> fraud.FraudValidationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_pb_fraud_fraud_proto_init() }
func file_shared_pb_fraud_fraud_proto_init() {
	if File_shared_pb_fraud_fraud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_pb_fraud_fraud_proto_rawDesc), len(file_shared_pb_fraud_fraud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_pb_fraud_fraud_proto_goTypes,
		DependencyIndexes: file_shared_pb_fraud_fraud_proto_depIdxs,
		MessageInfos:      file_shared_pb_fraud_fraud_proto_msgTypes,
	}.Build()
	File_shared_pb_fraud_fraud_proto = out.File
	file_shared_pb_fraud_fraud_proto_goTypes = nil
	file_shared_pb_fraud_fraud_proto_depIdxs = nil
}
